# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      admin.category:
            class: CatalogBundle\Admin\CategoryAdmin
            arguments: [~, CatalogBundle\Entity\Category, CatalogBundle:CategoryAdmin]
            tags:
                - { name: sonata.admin, manager_type: orm, group: catalog, label: Categories }
      admin.product:
            class: CatalogBundle\Admin\ProductAdmin
            arguments: [~, CatalogBundle\Entity\Product, CatalogBundle:ProductAdmin]
            tags:
            - { name: sonata.admin, manager_type: orm, group: catalog, label: Products }
