CatalogBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: CatalogBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        order_index:
          columns: [ order_in_catalog ]
    fields:
        title:
            type: string
            length: 255
        order_in_catalog:
            type: integer
        description:
            type: text
        isActive:
            type: boolean
            nullable: true
            column: is_active
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
               name: category_id
               referencedColumnName: id
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: product

    lifecycleCallbacks: {  }
